baseurl = "/"
title = "Chad Bixby"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Chad Bixby"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Chad Bixby"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "My Data Blog"
    description = "A place to share data driven discoveries"
    github = "https://github.com/XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "chadbixby15@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Projects"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

